import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import AdminHome from "./components/AdminHome.vue";
import ProductList from "./components/ProductList.vue";
import BrandList from "./components/BrandList.vue";
import TypeList from "./components/TypeList.vue";
import ColorList from "./components/ColorList.vue";
import SizeList from "./components/SizeList.vue";
import OrderPendingShipment from "./components/OrderPendingShipment.vue";
import OrderShipping from "./components/OrderShipping.vue";
import OrderSuccessful from "./components/OrderSuccessful.vue";
import OrderReturnApply from "./components/OrderReturnApply.vue";
import OrderReturned from "./components/OrderReturned.vue";
import OrderCancelled from "./components/OrderCancelled.vue";
import UserList from "./components/UserList.vue";
import ReportPerformance from "./components/ReportPerformance.vue";
import ReportMarketing from "./components/ReportMarketing.vue";
import ReportTraffic from "./components/ReportTraffic.vue";
import LinkManage from "./components/LinkManage.vue";
import AdManage from "./components/AdManage.vue";

const app = createApp(App);
app.use(router);
app.component("AdminHome", AdminHome);
app.component("ProductList", ProductList);
app.component("BrandList", BrandList);
app.component("TypeList", TypeList);
app.component("ColorList", ColorList);
app.component("SizeList", SizeList);
app.component("OrderPendingShipment", OrderPendingShipment);
app.component("OrderShipping", OrderShipping);
app.component("OrderSuccessful", OrderSuccessful);
app.component("OrderReturnApply", OrderReturnApply);
app.component("OrderReturned", OrderReturned);
app.component("OrderCancelled", OrderCancelled);
app.component("UserList", UserList);
app.component("ReportPerformance", ReportPerformance);
app.component("ReportMarketing", ReportMarketing);
app.component("ReportTraffic", ReportTraffic);
app.component("LinkManage", LinkManage);
app.component("AdManage", AdManage);
app.mount("#app");
